### ISSUE TITLE
voorbereiding pcb ontwerp designen in Altuim.

### ISSUE THREAD

**Issue by Reinvanderlinden** [cyrilknops/intelliflow#15]
Connectoren en componenten toevoegen in altium

**Comment by Glen-tech** [comment]
- ADC footprint en schematic is in orde gebracht
- Alle connectoren schematic en footprints zijn in orde ( 4 pins , 5 pins en 8 pins zelf moeten maken).

**DAC en ESP moet nog toegevoegt worden**

**Comment by Glen-tech** [comment]
ESP schematic gemaakt en toegevoegt  

ESP footprint , DAC + current to voltage moet nog worden toegevoegt.

**Comment by Glen-tech** [comment]
Alle footprints en 3d moddelen werden toegevoegt . Bewijs hiervan volgt nog.

**Comment by Glen-tech** [comment]
![afbeelding](https://user-images.githubusercontent.com/57532453/81154571-51db4100-8f84-11ea-813c-99858827f7e2.png)
![afbeelding](https://user-images.githubusercontent.com/57532453/81154629-615a8a00-8f84-11ea-936b-4374f46b436b.png)
