### ISSUE TITLE
Het opstellen van de elektrische schema voor breadboard prototype en test PCB's.

### ISSUE THREAD

**Issue by Reinvanderlinden** [cyrilknops/intelliflow#9]

**Comment by Glen-tech** [comment]
- ADC circuit is toegevoegt , alleen condensatoren en SPI verbinding zou nog gedaan moeten worden.
- DAC circuit moet nog volledig gedaan worden.

**Comment by Glen-tech** [comment]
Volledige test schema is afgerond 
![afbeelding](https://user-images.githubusercontent.com/57532453/81152284-18a1d180-8f82-11ea-8619-8d4eb865990f.png)
